require 'lib/foursquare'

FOURSQUARE = Foursquare::Base.new('YSQQ2G4HOATU5515IFH4ODCKUQYYKZ2M4DVBNPI1ZCXKL3QS')
# FOURSQUARE = Foursquare::Base.new('T2UPWWBXJP2UFBRTBXKDM1UQAH3A3TUDELQ3YQRFAWGLKTTT')
